export type NetworkConfig = {
    ENSCRIBE_CONTRACT: string;
    ENS_REGISTRY: string;
    BASE_REGISTRAR: string;
    NAME_WRAPPER: string;
    REVERSE_REGISTRAR: string;
    PUBLIC_RESOLVER: string;
    ENSCRIBE_DOMAIN: string;
    ETHERSCAN_URL: string;
    ENS_APP_URL: string;
    CHAINLENS_URL: string;
    BLOCKSCOUT_URL: string;
    RPC_ENDPOINT: string;
};

export const CONTRACTS: Record<number, NetworkConfig> = {
    // mainnet
    1: {
        ENSCRIBE_CONTRACT: process.env.NEXT_PUBLIC_ENSCRIBE_CONTRACT || "",
        ENS_REGISTRY: process.env.NEXT_PUBLIC_ENS_REGISTRY || "",
        BASE_REGISTRAR: process.env.NEXT_PUBLIC_ENS_BASE_REGISTRAR_IMPLEMENTATION || "",
        NAME_WRAPPER: process.env.NEXT_PUBLIC_NAME_WRAPPER || "",
        REVERSE_REGISTRAR: process.env.NEXT_PUBLIC_REVERSE_REGISTRAR || "",
        PUBLIC_RESOLVER: process.env.NEXT_PUBLIC_PUBLIC_RESOLVER || "",
        ENSCRIBE_DOMAIN: process.env.NEXT_PUBLIC_ENSCRIBE_DOMAIN || "",
        ETHERSCAN_URL: process.env.NEXT_PUBLIC_ETHERSCAN || "",
        ENS_APP_URL: process.env.NEXT_PUBLIC_ENS_APP || "",
        CHAINLENS_URL: process.env.NEXT_PUBLIC_CHAINLENS || "",
        BLOCKSCOUT_URL: process.env.NEXT_PUBLIC_BLOCKSCOUT || "",
        RPC_ENDPOINT: process.env.NEXT_PUBLIC_RPC || "",
    },
    // Sepolia Testnet
    11155111: {
        ENSCRIBE_CONTRACT: process.env.NEXT_PUBLIC_ENSCRIBE_CONTRACT_SEPOLIA || "",
        ENS_REGISTRY: process.env.NEXT_PUBLIC_ENS_REGISTRY_SEPOLIA || "",
        BASE_REGISTRAR: process.env.NEXT_PUBLIC_ENS_BASE_REGISTRAR_IMPLEMENTATION_SEPOLIA || "",
        NAME_WRAPPER: process.env.NEXT_PUBLIC_NAME_WRAPPER_SEPOLIA || "",
        REVERSE_REGISTRAR: process.env.NEXT_PUBLIC_REVERSE_REGISTRAR_SEPOLIA || "",
        PUBLIC_RESOLVER: process.env.NEXT_PUBLIC_PUBLIC_RESOLVER_SEPOLIA || "",
        ENSCRIBE_DOMAIN: process.env.NEXT_PUBLIC_ENSCRIBE_DOMAIN_SEPOLIA || "",
        ETHERSCAN_URL: process.env.NEXT_PUBLIC_ETHERSCAN_SEPOLIA || "",
        ENS_APP_URL: process.env.NEXT_PUBLIC_ENS_APP_SEPOLIA || "",
        CHAINLENS_URL: process.env.NEXT_PUBLIC_CHAINLENS_SEPOLIA || "",
        BLOCKSCOUT_URL: process.env.NEXT_PUBLIC_BLOCKSCOUT_SEPOLIA || "",
        RPC_ENDPOINT: process.env.NEXT_PUBLIC_RPC_SEPOLIA || "",
    },

    // Linea mainnet
    59144: {
        ENSCRIBE_CONTRACT: process.env.NEXT_PUBLIC_ENSCRIBE_CONTRACT_LINEA || "",
        ENS_REGISTRY: process.env.NEXT_PUBLIC_ENS_REGISTRY_LINEA || "",
        BASE_REGISTRAR: process.env.NEXT_PUBLIC_ENS_BASE_REGISTRAR_IMPLEMENTATION_LINEA || "",
        NAME_WRAPPER: process.env.NEXT_PUBLIC_NAME_WRAPPER_LINEA || "",
        REVERSE_REGISTRAR: process.env.NEXT_PUBLIC_REVERSE_REGISTRAR_LINEA || "",
        PUBLIC_RESOLVER: process.env.NEXT_PUBLIC_PUBLIC_RESOLVER_LINEA || "",
        ENSCRIBE_DOMAIN: process.env.NEXT_PUBLIC_ENSCRIBE_DOMAIN_LINEA || "",
        ETHERSCAN_URL: process.env.NEXT_PUBLIC_ETHERSCAN_LINEA || "",
        ENS_APP_URL: process.env.NEXT_PUBLIC_ENS_APP_LINEA || "",
        CHAINLENS_URL: process.env.NEXT_PUBLIC_CHAINLENS_LINEA || "",
        BLOCKSCOUT_URL: process.env.NEXT_PUBLIC_BLOCKSCOUT_LINEA || "",
        RPC_ENDPOINT: process.env.NEXT_PUBLIC_RPC_LINEA || "",
    },

    // Linea Sepolia Testnet
    59141: {
        ENSCRIBE_CONTRACT: process.env.NEXT_PUBLIC_ENSCRIBE_CONTRACT_LINEA_SEPOLIA || "",
        ENS_REGISTRY: process.env.NEXT_PUBLIC_ENS_REGISTRY_LINEA_SEPOLIA || "",
        BASE_REGISTRAR: process.env.NEXT_PUBLIC_ENS_BASE_REGISTRAR_IMPLEMENTATION_LINEA_SEPOLIA || "",
        NAME_WRAPPER: process.env.NEXT_PUBLIC_NAME_WRAPPER_LINEA_SEPOLIA || "",
        REVERSE_REGISTRAR: process.env.NEXT_PUBLIC_REVERSE_REGISTRAR_LINEA_SEPOLIA || "",
        PUBLIC_RESOLVER: process.env.NEXT_PUBLIC_PUBLIC_RESOLVER_LINEA_SEPOLIA || "",
        ENSCRIBE_DOMAIN: process.env.NEXT_PUBLIC_ENSCRIBE_DOMAIN_LINEA_SEPOLIA || "",
        ETHERSCAN_URL: process.env.NEXT_PUBLIC_ETHERSCAN_LINEA_SEPOLIA || "",
        ENS_APP_URL: process.env.NEXT_PUBLIC_ENS_APP_LINEA_SEPOLIA || "",
        CHAINLENS_URL: process.env.NEXT_PUBLIC_CHAINLENS_LINEA_SEPOLIA || "",
        BLOCKSCOUT_URL: process.env.NEXT_PUBLIC_BLOCKSCOUT_LINEA_SEPOLIA || "",
        RPC_ENDPOINT: process.env.NEXT_PUBLIC_RPC_LINEA_SEPOLIA || "",
    },

    // BASE mainnet
    8453: {
        ENSCRIBE_CONTRACT: process.env.NEXT_PUBLIC_ENSCRIBE_CONTRACT_BASE || "",
        ENS_REGISTRY: process.env.NEXT_PUBLIC_ENS_REGISTRY_BASE || "",
        BASE_REGISTRAR: process.env.NEXT_PUBLIC_ENS_BASE_REGISTRAR_IMPLEMENTATION_BASE || "",
        NAME_WRAPPER: process.env.NEXT_PUBLIC_NAME_WRAPPER_BASE || "",
        REVERSE_REGISTRAR: process.env.NEXT_PUBLIC_REVERSE_REGISTRAR_BASE || "",
        PUBLIC_RESOLVER: process.env.NEXT_PUBLIC_PUBLIC_RESOLVER_BASE || "",
        ENSCRIBE_DOMAIN: process.env.NEXT_PUBLIC_ENSCRIBE_DOMAIN_BASE || "",
        ETHERSCAN_URL: process.env.NEXT_PUBLIC_ETHERSCAN_BASE || "",
        ENS_APP_URL: process.env.NEXT_PUBLIC_ENS_APP_BASE || "",
        CHAINLENS_URL: process.env.NEXT_PUBLIC_CHAINLENS_BASE || "",
        BLOCKSCOUT_URL: process.env.NEXT_PUBLIC_BLOCKSCOUT_BASE || "",
        RPC_ENDPOINT: process.env.NEXT_PUBLIC_RPC_BASE || "",
    },

    // BASE Sepolia Testnet
    84532: {
        ENSCRIBE_CONTRACT: process.env.NEXT_PUBLIC_ENSCRIBE_CONTRACT_BASE_SEPOLIA || "",
        ENS_REGISTRY: process.env.NEXT_PUBLIC_ENS_REGISTRY_BASE_SEPOLIA || "",
        BASE_REGISTRAR: process.env.NEXT_PUBLIC_ENS_BASE_REGISTRAR_IMPLEMENTATION_BASE_SEPOLIA || "",
        NAME_WRAPPER: process.env.NEXT_PUBLIC_NAME_WRAPPER_BASE_SEPOLIA || "",
        REVERSE_REGISTRAR: process.env.NEXT_PUBLIC_REVERSE_REGISTRAR_BASE_SEPOLIA || "",
        PUBLIC_RESOLVER: process.env.NEXT_PUBLIC_PUBLIC_RESOLVER_BASE_SEPOLIA || "",
        ENSCRIBE_DOMAIN: process.env.NEXT_PUBLIC_ENSCRIBE_DOMAIN_BASE_SEPOLIA || "",
        ETHERSCAN_URL: process.env.NEXT_PUBLIC_ETHERSCAN_BASE_SEPOLIA || "",
        ENS_APP_URL: process.env.NEXT_PUBLIC_ENS_APP_BASE_SEPOLIA || "",
        CHAINLENS_URL: process.env.NEXT_PUBLIC_CHAINLENS_BASE_SEPOLIA || "",
        BLOCKSCOUT_URL: process.env.NEXT_PUBLIC_BLOCKSCOUT_BASE_SEPOLIA || "",
        RPC_ENDPOINT: process.env.NEXT_PUBLIC_RPC_BASE_SEPOLIA || "",
    },
};

export const TOPIC0 = process.env.NEXT_PUBLIC_TOPIC0_SET_NAME;

export const ETHERSCAN_API = process.env.NEXT_PUBLIC_ETHERSCAN_API;

export const SOURCIFY_API = process.env.NEXT_PUBLIC_SOURCIFY_API;
export const SOURCIFY_URL = process.env.NEXT_PUBLIC_SOURCIFY_URL;

export const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL || "";
export const SUPABASE_KEY = process.env.NEXT_PUBLIC_SUPABASE_KEY || "";

export enum CHAINS {
    MAINNET = 1,
    SEPOLIA = 11155111,
    LINEA = 59144,
    LINEA_SEPOLIA = 59141,
    BASE = 8453,
    BASE_SEPOLIA = 84532
}

export const METRICS_URL = '/api/v1/metrics'
export const NAME_GEN_URL = '/api/v1/name'
