export type NetworkConfig = {
    ENSCRIBE_CONTRACT: string;
    ENS_REGISTRY: string;
    BASE_REGISTRAR: string;
    NAME_WRAPPER: string;
    REVERSE_REGISTRAR: string;
    PUBLIC_RESOLVER: string;
    ENSCRIBE_DOMAIN: string;
    ETHERSCAN_URL: string;
    ENS_APP_URL: string;
    CHAINLENS_URL: string;
    ETHERSCAN_API: string;
};

export const CONTRACTS: Record<number, NetworkConfig> = {
    // Sepolia Testnet
    11155111: {
        ENSCRIBE_CONTRACT: process.env.NEXT_PUBLIC_ENSCRIBE_CONTRACT_SEPOLIA!,
        ENS_REGISTRY: process.env.NEXT_PUBLIC_ENS_REGISTRY_SEPOLIA!,
        BASE_REGISTRAR: process.env.NEXT_PUBLIC_ENS_BASE_REGISTRAR_IMPLEMENTATION_SEPOLIA!,
        NAME_WRAPPER: process.env.NEXT_PUBLIC_NAME_WRAPPER_SEPOLIA!,
        REVERSE_REGISTRAR: process.env.NEXT_PUBLIC_REVERSE_REGISTRAR_SEPOLIA!,
        PUBLIC_RESOLVER: process.env.NEXT_PUBLIC_PUBLIC_RESOLVER_SEPOLIA!,
        ENSCRIBE_DOMAIN: process.env.NEXT_PUBLIC_ENSCRIBE_DOMAIN_SEPOLIA!,
        ETHERSCAN_URL: process.env.NEXT_PUBLIC_ETHERSCAN_SEPOLIA!,
        ENS_APP_URL: process.env.NEXT_PUBLIC_ENS_APP_SEPOLIA!,
        CHAINLENS_URL: process.env.NEXT_PUBLIC_CHAINLENS_SEPOLIA!,
        ETHERSCAN_API: process.env.NEXT_PUBLIC_ETHERSCAN_API_SEPOLIA!
    },

    // Linea Sepolia Testnet
    59141: {
        ENSCRIBE_CONTRACT: process.env.NEXT_PUBLIC_ENSCRIBE_CONTRACT_LINEA_SEPOLIA!,
        ENS_REGISTRY: process.env.NEXT_PUBLIC_ENS_REGISTRY_LINEA_SEPOLIA!,
        BASE_REGISTRAR: process.env.NEXT_PUBLIC_ENS_BASE_REGISTRAR_IMPLEMENTATION_LINEA_SEPOLIA!,
        NAME_WRAPPER: process.env.NEXT_PUBLIC_NAME_WRAPPER_LINEA_SEPOLIA!,
        REVERSE_REGISTRAR: process.env.NEXT_PUBLIC_REVERSE_REGISTRAR_LINEA_SEPOLIA!,
        PUBLIC_RESOLVER: process.env.NEXT_PUBLIC_PUBLIC_RESOLVER_LINEA_SEPOLIA!,
        ENSCRIBE_DOMAIN: process.env.NEXT_PUBLIC_ENSCRIBE_DOMAIN_LINEA_SEPOLIA!,
        ETHERSCAN_URL: process.env.NEXT_PUBLIC_ETHERSCAN_LINEA_SEPOLIA!,
        ENS_APP_URL: process.env.NEXT_PUBLIC_ENS_APP_LINEA_SEPOLIA!,
        CHAINLENS_URL: process.env.NEXT_PUBLIC_CHAINLENS_LINEA_SEPOLIA!,
        ETHERSCAN_API: process.env.NEXT_PUBLIC_ETHERSCAN_API_LINEA_SEPOLIA!
    },
};

export const TOPIC0 = process.env.NEXT_PUBLIC_TOPIC0_SET_NAME;