import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  
  // Guide sidebar with manual configuration for proper labels
  guidesSidebar: [
    {
      type: 'doc',
      id: 'index',
      label: 'Welcome to the Guides',
    },
    {
      type: 'doc',
      id: 'common-patterns',
      label: 'Common Patterns',
    },
    {
      type: 'category',
      label: 'How To Guides',
      items: [
        {type: 'autogenerated', dirName: 'how-to-guides'}
      ],
    },
    {
      type: 'category',
      label: 'Knowledge Guides',
      items: [
        {type: 'autogenerated', dirName: 'knowledge-guides'}
      ],
    },
  ],
};

export default sidebars;
